SELECT SETTLEMENT.*
FROM SETTLEMENT INNER JOIN CLIENT ON CLIENT.CLIENTCODE = SETTLEMENT.CLIENTCODE
WHERE DATEOFEVICTION > DATE(2007-07-01) AND DATEOFEVICTION < DATE(2007-12-31);
  
SELECT CLIENT.* 
FROM CLIENT JOIN SETTLEMENT ON SETTLEMENT.CLIENTCODE = CLIENT.CLIENTCODE
WHERE SETTLEMENT.DATEOFEVICTION > (SELECT SYSDATE FROM DUAL) AND SETTLEMENT.DATEOFSETTLEMENT < (SELECT SYSDATE FROM DUAL);
  
SELECT EXTRACT(year from SETTLEMENT.DATEOFEVICTION) as onlyYear, extract(month from SETTLEMENT.DATEOFEVICTION) as onlyMonth, COUNT(CLIENT.CLIENTCODE) AS CLIENTCOUNT
FROM SETTLEMENT JOIN CLIENT ON CLIENT.CLIENTCODE = SETTLEMENT.CLIENTCODE
GROUP BY EXTRACT(year from SETTLEMENT.DATEOFEVICTION), EXTRACT(month from SETTLEMENT.DATEOFEVICTION)
ORDER BY onlyYear, onlyMonth;
