INSERT ALL
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (1, 'Иван', 'Иванов', 'Иванович', '1234567890', 'Хороший человек')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (2, 'Олег', 'Блинов', 'Олегович', '1241421512', 'Нехороший человек')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (3, 'Руслана', 'Бахтиешь', 'Ульна', '1747285379', 'Не убирать в номере')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (4, 'Соня', 'Миризе', 'Владлена', '1942682380', 'Доставка кадый день')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (5, 'Тимофей', 'Вавилов', 'Олегов', '1209876542', 'Спец. питание')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (6, 'Леха', 'Тимофеев', 'Олегович', '3456789098', 'Требуется доп.кровать')
    INTO CLIENT (CLIENTCODE, CLIENTNAME, CLIENTSURNAME, CLIENTPATRONYMIC, PASPORTDATA, COMMENTABOUTCLIENTS) VALUES (7, 'Гриша', 'Министров', 'Министор', '677645543', 'Хороший человек')
SELECT * FROM dual; 

INSERT ALL
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (1, 1, 1, 'Стандарт', 2000)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (2, 2, 2, 'Комфорт', 4000)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (3, 3, 2, 'Комфорт', 4500)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (4, 4, 3, 'Стандарт', 2500)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (5, 5, 4, 'Комфорт', 4400)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (6, 6, 4, 'Люкс', 11000)
    INTO ROOM (ROOMCODE, ROOMNUMBER, NUMBEROFSEATS, ROOMCOMFORT, PRICEPERDAY) VALUES (7, 7, 5, 'Люкс', 9500)
SELECT * FROM dual;

INSERT ALL
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (1, 7, 2, DATE '2007-07-01', DATE '2007-07-21', 'Живет с собакой')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (2, 1, 3, DATE '2007-08-11', DATE '2007-08-21', 'Не любит шум')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (3, 2, 1, DATE '2007-10-21', DATE '2007-11-30', 'Сильно шумит по ночам')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (4, 4, 4, DATE '2008-01-15', DATE '2007-01-25', 'Лунатик')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (5, 3, 6, DATE '2008-02-29', DATE '2007-03-05', 'Храпит')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (6, 5, 5, DATE '2007-05-05', DATE '2007-05-15', 'Сам собака')
    INTO SETTLEMENT (SETTLEMENTCODE, CLIENTCODE, ROOMCODE, DATEOFSETTLEMENT, DATEOFEVICTION, CHEKINNOTE) VALUES (7, 6, 7, DATE '2007-03-02', DATE '2007-03-20', 'Не любит собак')
SELECT * FROM dual;